# config.yaml

data:
  ticker: 'AAPL'
  start_date: '2015-01-01'
  end_date: '2023-01-01'

model:
  supervised:
    type: 'xgboost'
    parameters:
      n_estimators: 100
      max_depth: 5
      learning_rate: 0.1

risk_management:
  risk_per_trade: 0.01

backtesting:
  initial_capital: 10000
